{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5145", 
                "published": "2015-07-14T13:59:08.400-04:00", 
                "id": "CVE-2015-5145", 
                "modified": "2015-07-15T14:53:27.480-04:00", 
                "summary": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/399.html", 
                "id": "CWE-399", 
                "title": "Resource Management Errors"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:djangoproject:django:1.8.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.0"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.76398", 
                "id": 76398
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "6.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "none", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "7.8", 
                    "integrity impact": "none", 
                    "availability impact": "complete", 
                    "access vector": "network"
                }
            ], 
            "severity": "High", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2015-5145"
    }, 
    "Scanners": {
        "Oval": [], 
        "Nmap": [], 
        "OpenVas": [], 
        "Nessus": [
            {
                "name": "Fedora 22 : python-django-1.8.3-1.fc22 (2015-11403)", 
                "file": "fedora_2015-11403.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "84968"
            }, 
            {
                "name": "FreeBSD : django -- multiple vulnerabilities (37ed8e9c-2651-11e5-86ff-14dae9d210b8)", 
                "file": "freebsd_pkg_37ed8e9c265111e586ff14dae9d210b8.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "84652"
            }, 
            {
                "name": "GLSA-201510-06 : Django: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201510-06.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "86691"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [], 
        "Debian": [], 
        "Vmware": []
    }
}