{
    "Information": {
        "Category": [
            {
                "url": "https://cwe.mitre.org/data/definitions/118.html", 
                "id": "CWE-118", 
                "title": "Improper Access of Indexable Resource (Range Error)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/20.html", 
                "id": "CWE-20", 
                "title": "Improper Input Validation"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/726.html", 
                "id": "CWE-726", 
                "title": "OWASP Top Ten 2004 Category A5 - Buffer Overflows"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/633.html", 
                "id": "CWE-633", 
                "title": "Weaknesses that Affect Memory"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/740.html", 
                "id": "CWE-740", 
                "title": "CERT C Secure Coding Section 06 - Arrays (ARR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/741.html", 
                "id": "CWE-741", 
                "title": "CERT C Secure Coding Section 07 - Characters and Strings (STR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/742.html", 
                "id": "CWE-742", 
                "title": "CERT C Secure Coding Section 08 - Memory Management (MEM)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/743.html", 
                "id": "CWE-743", 
                "title": "CERT C Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/744.html", 
                "id": "CWE-744", 
                "title": "CERT C Secure Coding Section 10 - Environment (ENV)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/752.html", 
                "id": "CWE-752", 
                "title": "2009 Top 25 - Risky Resource Management"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/874.html", 
                "id": "CWE-874", 
                "title": "CERT C++ Secure Coding Section 06 - Arrays and the STL (ARR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/875.html", 
                "id": "CWE-875", 
                "title": "CERT C++ Secure Coding Section 07 - Characters and Strings (STR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/876.html", 
                "id": "CWE-876", 
                "title": "CERT C++ Secure Coding Section 08 - Memory Management (MEM)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/877.html", 
                "id": "CWE-877", 
                "title": "CERT C++ Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/878.html", 
                "id": "CWE-878", 
                "title": "CERT C++ Secure Coding Section 10 - Environment (ENV)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/970.html", 
                "id": "CWE-970", 
                "title": "SFP Secondary Cluster: Faulty Buffer Access"
            }
        ], 
        "CAPEC": [
            {
                "url": "https://capec.mitre.org/data/definitions/10.html", 
                "id": 10
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/100.html", 
                "id": 100
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/14.html", 
                "id": 14
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/24.html", 
                "id": 24
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/42.html", 
                "id": 42
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/44.html", 
                "id": 44
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/45.html", 
                "id": 45
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/46.html", 
                "id": 46
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/47.html", 
                "id": 47
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/8.html", 
                "id": 8
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/9.html", 
                "id": 9
            }
        ], 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-3142", 
                "published": "2008-08-01T10:41:00.000-04:00", 
                "id": "CVE-2008-3142", 
                "modified": "2011-03-07T22:10:16.453-05:00", 
                "summary": "Multiple buffer overflows in Python 2.5.2 and earlier on 32bit platforms allow context-dependent attackers to cause a denial of service (crash) or have unspecified other impact via a long string that leads to incorrect memory allocation during Unicode string processing, related to the unicode_resize function and the PyMem_RESIZE macro."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/119.html", 
                "id": "CWE-119", 
                "title": "Improper Restriction of Operations within the Bounds of a Memory Buffer"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.7"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.6"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.0"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.6.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.5.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.6"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.0.1"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.43495", 
                "id": 43495
            }
        ], 
        "IAVM": [], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/30491", 
                "id": 30491
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "http://xforce.iss.net/xforce/xfdb/44173", 
                    "vendor": "XF"
                }, 
                {
                    "url": "http://xforce.iss.net/xforce/xfdb/44170", 
                    "vendor": "XF"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2009/3316", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2008/2288", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vmware.com/security/advisories/VMSA-2009-0016.html", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/usn-632-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/30491", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded", 
                    "vendor": "BUGTRAQ"
                }, 
                {
                    "url": "http://www.securityfocus.com/archive/1/archive/1/495445/100/0/threaded", 
                    "vendor": "BUGTRAQ"
                }, 
                {
                    "url": "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://www.debian.org/security/2008/dsa-1667", 
                    "vendor": "DEBIAN"
                }, 
                {
                    "url": "http://wiki.rpath.com/Advisories:rPSA-2008-0243", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://support.apple.com/kb/HT3438", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289", 
                    "vendor": "SLACKWARE"
                }, 
                {
                    "url": "http://security.gentoo.org/glsa/glsa-200807-16.xml", 
                    "vendor": "GENTOO"
                }, 
                {
                    "url": "http://secunia.com/advisories/37471", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/33937", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/32793", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31687", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31518", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31473", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31365", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31358", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31332", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/31305", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html", 
                    "vendor": "APPLE"
                }, 
                {
                    "url": "http://bugs.python.org/issue2620", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/file10825/issue2620-gps02-patch.txt", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.gentoo.org/show_bug.cgi?id=232137", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "6.4", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "7.5", 
                    "integrity impact": "partial", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "High", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2008-3142"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17381", 
                "title": "USN-632-1 -- python2.4, python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17381"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:7901", 
                "title": "DSA-1667 python2.4 -- several vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:7901"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:29294", 
                "title": "RHSA-2009:1176 -- python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:29294"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:19316", 
                "title": "DSA-1667-1 python2.4 - several vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:19316"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:11466", 
                "title": "Multiple buffer overflows in Python 2.5.2 and earlier on 32bit platforms allow context-dependent attackers to cause a denial of service (crash) or have unspecified other impact via a long string that leads to incorrect memory allocation during Unicode string processing, related to the unicode_resize function and the PyMem_RESIZE macro.", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:11466"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:22809", 
                "title": "ELSA-2009:1176: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:22809"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:8422", 
                "title": "VMware python multiple buffer overflows vulnerability", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:8422"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Debian Security Advisory DSA 1667-1 (python2.4)", 
                "file": "deb_1667_1.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "61905"
            }, 
            {
                "name": "Slackware Advisory SSA:2008-217-01 python ", 
                "file": "esoft_slk_ssa_2008_217_01.nasl", 
                "family": "Slackware Local Security Checks", 
                "id": "61467"
            }, 
            {
                "name": "FreeBSD Ports: python24", 
                "file": "freebsd_python24.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "61617"
            }, 
            {
                "name": "CentOS Update for python CESA-2009:1176 centos5 i386", 
                "file": "gb_CESA-2009_1176_python_centos5_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880881"
            }, 
            {
                "name": "CentOS Update for python CESA-2009:1178 centos3 i386", 
                "file": "gb_CESA-2009_1178_python_centos3_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880715"
            }, 
            {
                "name": "Mandriva Update for mysql MDVA-2012:049 (mysql)", 
                "file": "gb_mandriva_MDVSA_2008_163.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "830740"
            }, 
            {
                "name": "Ubuntu Update for erlang vulnerability USN-624-2", 
                "file": "gb_ubuntu_USN_632_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "840343"
            }, 
            {
                "name": "Gentoo Security Advisory GLSA 200807-16 (python)", 
                "file": "glsa_200807_16.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "61391"
            }, 
            {
                "name": "get_kb_item(ssh/login/osx_name", 
                "file": "macosx_secupd_2009-001.nasl", 
                "family": "Mac OS X Local Security Checks", 
                "id": "102026"
            }, 
            {
                "name": "CentOS Security Advisory CESA-2009:1176 (python)", 
                "file": "ovcesa2009_1176.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "64583"
            }, 
            {
                "name": "CentOS Security Advisory CESA-2009:1178 (python)", 
                "file": "ovcesa2009_1178.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "64493"
            }, 
            {
                "name": "RedHat Security Advisory RHSA-2009:1176", 
                "file": "RHSA_2009_1176.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "64453"
            }, 
            {
                "name": "RedHat Security Advisory RHSA-2009:1177", 
                "file": "RHSA_2009_1177.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "64454"
            }, 
            {
                "name": "RedHat Security Advisory RHSA-2009:1178", 
                "file": "RHSA_2009_1178.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "64455"
            }, 
            {
                "name": "Python Multiple Vulnerabilities (Linux)", 
                "file": "secpod_python_mult_vuln_lin_900106.nasl", 
                "family": "Buffer overflow", 
                "id": "900106"
            }, 
            {
                "name": "SLES10: Security update for Python", 
                "file": "sles10_python.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "65883"
            }, 
            {
                "name": "SLES9: Security update for Python", 
                "file": "sles9p5032900.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "65027"
            }
        ], 
        "Nessus": [
            {
                "name": "CentOS 5 : python (CESA-2009:1176)", 
                "file": "centos_RHSA-2009-1176.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "43771"
            }, 
            {
                "name": "CentOS 3 : python (CESA-2009:1178)", 
                "file": "centos_RHSA-2009-1178.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "40394"
            }, 
            {
                "name": "Debian DSA-1667-1 : python2.4 - several vulnerabilities", 
                "file": "debian_DSA-1667.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "34823"
            }, 
            {
                "name": "FreeBSD : python -- multiple vulnerabilities (0dccaa28-7f3c-11dd-8de5-0030843d3802)", 
                "file": "freebsd_pkg_0dccaa287f3c11dd8de50030843d3802.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "34164"
            }, 
            {
                "name": "GLSA-200807-16 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-200807-16.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "33782"
            }, 
            {
                "name": "Mac OS X Multiple Vulnerabilities (Security Update 2009-001)", 
                "file": "macosx_SecUpd2009-001.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "35684"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2008:163)", 
                "file": "mandriva_MDVSA-2008-163.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "37212"
            }, 
            {
                "name": "Oracle Linux 5 : python (ELSA-2009-1176)", 
                "file": "oraclelinux_ELSA-2009-1176.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "67896"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2009-1177)", 
                "file": "oraclelinux_ELSA-2009-1177.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "67897"
            }, 
            {
                "name": "Oracle Linux 3 : python (ELSA-2009-1178)", 
                "file": "oraclelinux_ELSA-2009-1178.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "67898"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2009:1176)", 
                "file": "redhat-RHSA-2009-1176.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "40400"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2009:1177)", 
                "file": "redhat-RHSA-2009-1177.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "40401"
            }, 
            {
                "name": "RHEL 3 : python (RHSA-2009:1178)", 
                "file": "redhat-RHSA-2009-1178.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "40402"
            }, 
            {
                "name": "Scientific Linux Security Update : python for SL5.x i386/x86_64", 
                "file": "sl_20090727_python_for_SL5_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60622"
            }, 
            {
                "name": "Scientific Linux Security Update : python for SL 3.0.x on i386/x86_64", 
                "file": "sl_20090728_python_for_SL_3_0_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60624"
            }, 
            {
                "name": "Scientific Linux Security Update : python for SL 4.x on i386/x86_64", 
                "file": "sl_20090728_python_for_SL_4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60625"
            }, 
            {
                "name": "Slackware 10.1 / 10.2 / 11.0 / 12.0 / 12.1 / current : python (SSA:2008-217-01)", 
                "file": "Slackware_SSA_2008-217-01.nasl", 
                "family": "Slackware Local Security Checks", 
                "id": "33824"
            }, 
            {
                "name": "SuSE9 Security Update : Python (YOU Patch Number 12215)", 
                "file": "suse9_12215.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "41229"
            }, 
            {
                "name": "openSUSE Security Update : python (python-128)", 
                "file": "suse_11_0_python-080801.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "40115"
            }, 
            {
                "name": "SuSE 10 Security Update : Python (ZYPP Patch Number 5490)", 
                "file": "suse_python-5490.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "33923"
            }, 
            {
                "name": "openSUSE 10 Security Update : python (python-5491)", 
                "file": "suse_python-5491.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "33924"
            }, 
            {
                "name": "Ubuntu 6.06 LTS / 7.04 / 7.10 / 8.04 LTS : python2.4, python2.5 vulnerabilities (USN-632-1)", 
                "file": "ubuntu_USN-632-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "33807"
            }, 
            {
                "name": "VMSA-2009-0016 : VMware vCenter and ESX update release and vMA patch release address multiple security issues in third party components.", 
                "file": "vmware_VMSA-2009-0016.nasl", 
                "family": "VMware ESX Local Security Checks", 
                "id": "42870"
            }, 
            {
                "name": "VMware ESX / ESXi Multiple Vulnerabilities (VMSA-2009-0016) (remote check)", 
                "file": "vmware_VMSA-2009-0016_remote.nasl", 
                "family": "Misc.", 
                "id": "89117"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163", 
                "id": "MDVSA-2008:163"
            }, 
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164", 
                "id": "MDVSA-2008:164"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2008-3142.html", 
                "id": "SUSE-SR:2008:017"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20091176", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2009-1176.html", 
                    "id": "RHSA-2009:1176", 
                    "title": "RHSA-2009:1176: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=235093", 
                    "title": "CVE-2007-2052 python off-by-one locale.strxfrm() (possible memory disclosure)", 
                    "id": "235093", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=295971", 
                    "title": "CVE-2007-4965 python imageop module heap corruption", 
                    "id": "295971", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=442005", 
                    "title": "CVE-2008-1721 python: integer signedness error in the zlib extension module", 
                    "id": "442005", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=443810", 
                    "title": "CVE-2008-1887 python: PyString_FromStringAndSize does not check for negative size values", 
                    "id": "443810", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=454990", 
                    "title": "CVE-2008-3142 python: Multiple buffer overflows in unicode processing", 
                    "id": "454990", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455008", 
                    "title": "CVE-2008-2315 python: Multiple integer overflows in python core", 
                    "id": "455008", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455013", 
                    "title": "CVE-2008-3143 python: Multiple integer overflows discovered by Google", 
                    "id": "455013", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455018", 
                    "title": "CVE-2008-3144 python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function", 
                    "id": "455018", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=469656", 
                    "title": "CVE-2008-4864 python: imageop module multiple integer overflows", 
                    "id": "469656", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=470915", 
                    "title": "CVE-2008-5031 python: stringobject, unicodeobject integer overflows", 
                    "id": "470915", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1176"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20091177", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2009-1177.html", 
                    "id": "RHSA-2009:1177", 
                    "title": "RHSA-2009:1177: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=441306", 
                    "title": "CVE-2008-1679 python: imageop module integer overflows", 
                    "id": "441306", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=442005", 
                    "title": "CVE-2008-1721 python: integer signedness error in the zlib extension module", 
                    "id": "442005", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=443810", 
                    "title": "CVE-2008-1887 python: PyString_FromStringAndSize does not check for negative size values", 
                    "id": "443810", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=454990", 
                    "title": "CVE-2008-3142 python: Multiple buffer overflows in unicode processing", 
                    "id": "454990", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455008", 
                    "title": "CVE-2008-2315 python: Multiple integer overflows in python core", 
                    "id": "455008", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455013", 
                    "title": "CVE-2008-3143 python: Multiple integer overflows discovered by Google", 
                    "id": "455013", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455018", 
                    "title": "CVE-2008-3144 python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function", 
                    "id": "455018", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=469656", 
                    "title": "CVE-2008-4864 python: imageop module multiple integer overflows", 
                    "id": "469656", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=470915", 
                    "title": "CVE-2008-5031 python: stringobject, unicodeobject integer overflows", 
                    "id": "470915", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1177"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20091178", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2009-1178.html", 
                    "id": "RHSA-2009:1178", 
                    "title": "RHSA-2009:1178: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=441306", 
                    "title": "CVE-2008-1679 python: imageop module integer overflows", 
                    "id": "441306", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=443810", 
                    "title": "CVE-2008-1887 python: PyString_FromStringAndSize does not check for negative size values", 
                    "id": "443810", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=454990", 
                    "title": "CVE-2008-3142 python: Multiple buffer overflows in unicode processing", 
                    "id": "454990", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455008", 
                    "title": "CVE-2008-2315 python: Multiple integer overflows in python core", 
                    "id": "455008", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455013", 
                    "title": "CVE-2008-3143 python: Multiple integer overflows discovered by Google", 
                    "id": "455013", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=455018", 
                    "title": "CVE-2008-3144 python: Potential integer underflow and overflow in the PyOS_vsnprintf C API function", 
                    "id": "455018", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=469656", 
                    "title": "CVE-2008-4864 python: imageop module multiple integer overflows", 
                    "id": "469656", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=470915", 
                    "title": "CVE-2008-5031 python: stringobject, unicodeobject integer overflows", 
                    "id": "470915", 
                    "issue date": "2009-07-27", 
                    "associated redhat": "RHSA-2009:1178"
                }
            }
        ], 
        "Gentoo": [
            {
                "url": "https://security.gentoo.org/glsa/200807-16", 
                "id": "GLSA-200807-16"
            }
        ], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-632-1", 
                "id": "USN-632-1"
            }
        ], 
        "Debian": [
            {
                "url": "https://security-tracker.debian.org/tracker/DSA-1667", 
                "id": "DSA-1667"
            }
        ], 
        "Vmware": [
            {
                "url": "https://www.vmware.com/security/advisories/VMSA-2009-0016.html", 
                "id": "VMSA-2009-0016"
            }
        ]
    }
}