{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-1449", 
                "published": "2010-05-27T15:30:01.703-04:00", 
                "id": "CVE-2010-1449", 
                "modified": "2011-03-01T02:01:54.287-05:00", 
                "summary": "Integer overflow in rgbimgmodule.c in the rgbimg module in Python 2.5 allows remote attackers to have an unspecified impact via a large image that triggers a buffer overflow.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2008-3143.12."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/189.html", 
                "id": "CWE-189", 
                "title": "Numeric Errors"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:2.5"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.53379", 
                "id": 53379
            }
        ], 
        "IAVM": [], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/40363", 
                "id": 40363
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0413", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0212", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0122", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/40363", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.redhat.com/support/errata/RHSA-2011-0260.html", 
                    "vendor": "REDHAT"
                }, 
                {
                    "url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html", 
                    "vendor": "REDHAT"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://support.apple.com/kb/HT4435", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://secunia.com/advisories/43364", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/43068", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/42888", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html", 
                    "vendor": "APPLE"
                }, 
                {
                    "url": "http://bugs.python.org/issue8678", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "6.4", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "7.5", 
                    "integrity impact": "partial", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "High", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2010-1449"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28118", 
                "title": "DEPRECATED: ELSA-2011-0027 -- python security, bug fix, and enhancement update (low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28118"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:22821", 
                "title": "ELSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:22821"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21921", 
                "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21921"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Mac OS X v10.6.4 Multiple Vulnerabilities (2010-007)", 
                "file": "gb_macosx_su10-007.nasl", 
                "family": "Mac OS X Local Security Checks", 
                "id": "802144"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2010:215 (python)", 
                "file": "gb_mandriva_MDVSA_2010_215.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831224"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0027-01", 
                "file": "gb_RHSA-2011_0027-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870377"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0260-01", 
                "file": "gb_RHSA-2011_0260-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870395"
            }
        ], 
        "Nessus": [
            {
                "name": "Mac OS X 10.6 < 10.6.5 Multiple Vulnerabilities", 
                "file": "macosx_10_6_5.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "50548"
            }, 
            {
                "name": "Mac OS X Multiple Vulnerabilities (Security Update 2010-007)", 
                "file": "macosx_SecUpd2010-007.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "50549"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2010:215)", 
                "file": "mandriva_MDVSA-2010-215.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "50423"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2011-0260)", 
                "file": "oraclelinux_ELSA-2011-0260.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68201"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0027)", 
                "file": "redhat-RHSA-2011-0027.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "51524"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2011:0260)", 
                "file": "redhat-RHSA-2011-0260.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "52007"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL5.x i386/x86_64", 
                "file": "sl_20110113_python_on_SL5_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60935"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL4.x i386/x86_64", 
                "file": "sl_20110216_python_on_SL4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60960"
            }, 
            {
                "name": "SuSE 10 Security Update : Python (ZYPP Patch Number 7314)", 
                "file": "suse_python-7314.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "51642"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215", 
                "id": "MDVSA-2010:215"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2010-1449.html", 
                "id": "SUSE-SR:2011:002"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110027", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0027.html", 
                    "id": "RHSA-2011:0027", 
                    "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=482814", 
                    "title": "CVE-2008-5983 python: untrusted python modules search path", 
                    "id": "482814", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698", 
                    "title": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues", 
                    "id": "541698", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=569093", 
                    "title": "Python 2.4's arena allocator does not release memory back to the system, leading to \"high-water mark\" memory usage", 
                    "id": "569093", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609017", 
                    "title": "subprocess leaves open fds on construction error", 
                    "id": "609017", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609020", 
                    "title": "subprocess fails in select when descriptors are large", 
                    "id": "609020", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625372", 
                    "title": "split python-libs subpackage", 
                    "id": "625372", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644147", 
                    "title": "Patch for get_filename in email.message when content-disposition is missing", 
                    "id": "644147", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644761", 
                    "title": "python-libs conflict on ia64 compatlayer", 
                    "id": "644761", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110260", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0260.html", 
                    "id": "RHSA-2011:0260", 
                    "title": "RHSA-2011:0260: python security and bug fix update (Low)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=497540", 
                    "title": "grp module does not support whole uid/gid range", 
                    "id": "497540", 
                    "issue date": "2011-02-16", 
                    "associated redhat": "RHSA-2011:0260"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698", 
                    "title": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues", 
                    "id": "541698", 
                    "issue date": "2011-02-16", 
                    "associated redhat": "RHSA-2011:0260"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [], 
        "Debian": [], 
        "Vmware": []
    }
}