{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-5983", 
                "published": "2009-01-27T21:30:00.233-05:00", 
                "id": "CVE-2008-5983", 
                "modified": "2013-05-14T22:49:35.770-04:00", 
                "summary": "Untrusted search path vulnerability in the PySys_SetArgv API function in Python 2.6 and earlier, and possibly later versions, prepends an empty string to sys.path when the argv[0] argument does not contain a path separator, which might allow local users to execute arbitrary code via a Trojan horse Python file in the current working directory."
            }
        ], 
        "CWE": null, 
        "CPE": [
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.6.0"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.7"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4.6"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.6"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.0"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.6.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.5"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.5.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.2"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.2.3"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:1.6"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.1.1"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.4"
            }, 
            {
                "id": "cpe:/a:python_software_foundation:python:2.0.1"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.46121", 
                "id": 46121
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=482814", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2011/0122", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.vupen.com/english/advisories/2010/1448", 
                    "vendor": "VUPEN"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1616-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html", 
                    "vendor": "REDHAT"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2009/01/30/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2009/01/28/5", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2009/01/26/2", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.nabble.com/Bug-484305%3A-bicyclerepair%3A-bike.vim-imports-untrusted-python-files-from-cwd-td18848099.html", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg586010.html", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://security.gentoo.org/glsa/glsa-200904-06.xml", 
                    "vendor": "GENTOO"
                }, 
                {
                    "url": "http://security.gentoo.org/glsa/glsa-200903-41.xml", 
                    "vendor": "GENTOO"
                }, 
                {
                    "url": "http://secunia.com/advisories/51087", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51040", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51024", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/50858", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/42888", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/40194", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/34522", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://lists.fedoraproject.org/pipermail/package-announce/2010-June/042751.html", 
                    "vendor": "FEDORA"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "10.0", 
                    "access complexity": "medium", 
                    "confidentiality impact": "complete", 
                    "authentication": "none", 
                    "exploit": "3.4", 
                    "base": "6.9", 
                    "integrity impact": "complete", 
                    "availability impact": "complete", 
                    "access vector": "local"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2008-5983"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17830", 
                "title": "USN-1613-1 -- python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17830"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28118", 
                "title": "DEPRECATED: ELSA-2011-0027 -- python security, bug fix, and enhancement update (low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28118"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17941", 
                "title": "USN-1616-1 -- python3.1 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17941"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:22821", 
                "title": "ELSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:22821"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21921", 
                "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21921"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18020", 
                "title": "USN-1613-2 -- python2.4 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18020"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18043", 
                "title": "USN-1596-1 -- python2.6 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18043"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Fedora Core 10 FEDORA-2009-1289 (gnumeric)", 
                "file": "fcore_2009_1289.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "63330"
            }, 
            {
                "name": "FreeBSD Ports: epiphany", 
                "file": "freebsd_epiphany.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "63564"
            }, 
            {
                "name": "Fedora Update for python3 FEDORA-2010-13388", 
                "file": "gb_fedora_2010_13388_python3_fc13.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862373"
            }, 
            {
                "name": "Fedora Update for python FEDORA-2010-9565", 
                "file": "gb_fedora_2010_9565_python_fc12.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862218"
            }, 
            {
                "name": "Fedora Update for python FEDORA-2010-9652", 
                "file": "gb_fedora_2010_9652_python_fc13.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "862160"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0027-01", 
                "file": "gb_RHSA-2011_0027-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870377"
            }, 
            {
                "name": "Ubuntu Update for python2.6 USN-1596-1", 
                "file": "gb_ubuntu_USN_1596_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841178"
            }, 
            {
                "name": "Ubuntu Update for python2.5 USN-1613-1", 
                "file": "gb_ubuntu_USN_1613_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841195"
            }, 
            {
                "name": "Ubuntu Update for python2.4 USN-1613-2", 
                "file": "gb_ubuntu_USN_1613_2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841194"
            }, 
            {
                "name": "Ubuntu Update for python3.1 USN-1616-1", 
                "file": "gb_ubuntu_USN_1616_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841199"
            }, 
            {
                "name": "Gentoo Security Advisory GLSA 200903-41 (gedit)", 
                "file": "glsa_200903_41.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "63738"
            }, 
            {
                "name": "Gentoo Security Advisory GLSA 200904-06 (eog)", 
                "file": "glsa_200904_06.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "63800"
            }
        ], 
        "Nessus": [
            {
                "name": "Fedora 9 : gnumeric-1.8.2-4.fc9 (2009-1295)", 
                "file": "fedora_2009-1295.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "35596"
            }, 
            {
                "name": "Fedora 13 : python3-3.1.2-7.fc13 (2010-13388)", 
                "file": "fedora_2010-13388.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "49107"
            }, 
            {
                "name": "Fedora 12 : python-2.6.2-8.fc12 (2010-9565)", 
                "file": "fedora_2010-9565.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "47600"
            }, 
            {
                "name": "Fedora 13 : python-2.6.4-27.fc13 (2010-9652)", 
                "file": "fedora_2010-9652.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "47547"
            }, 
            {
                "name": "FreeBSD : epiphany -- untrusted search path vulnerability (e848a92f-0e7d-11de-92de-000bcdc1757a)", 
                "file": "freebsd_pkg_e848a92f0e7d11de92de000bcdc1757a.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "35910"
            }, 
            {
                "name": "GLSA-200903-41 : gedit: Untrusted search path", 
                "file": "gentoo_GLSA-200903-41.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "36055"
            }, 
            {
                "name": "GLSA-200904-06 : Eye of GNOME: Untrusted search path", 
                "file": "gentoo_GLSA-200904-06.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "36094"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0027)", 
                "file": "redhat-RHSA-2011-0027.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "51524"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL5.x i386/x86_64", 
                "file": "sl_20110113_python_on_SL5_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "60935"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 / 11.10 : python2.6 vulnerabilities (USN-1596-1)", 
                "file": "ubuntu_USN-1596-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62436"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.5 vulnerabilities (USN-1613-1)", 
                "file": "ubuntu_USN-1613-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62619"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.4 vulnerabilities (USN-1613-2)", 
                "file": "ubuntu_USN-1613-2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62620"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 : python3.1 vulnerabilities (USN-1616-1)", 
                "file": "ubuntu_USN-1616-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62700"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [
            {
                "url": "https://admin.fedoraproject.org/updates/FEDORA-2010-9652", 
                "id": "FEDORA-2010-9652"
            }
        ], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110027", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0027.html", 
                    "id": "RHSA-2011:0027", 
                    "title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=482814", 
                    "title": "CVE-2008-5983 python: untrusted python modules search path", 
                    "id": "482814", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698", 
                    "title": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues", 
                    "id": "541698", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=569093", 
                    "title": "Python 2.4's arena allocator does not release memory back to the system, leading to \"high-water mark\" memory usage", 
                    "id": "569093", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609017", 
                    "title": "subprocess leaves open fds on construction error", 
                    "id": "609017", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=609020", 
                    "title": "subprocess fails in select when descriptors are large", 
                    "id": "609020", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625372", 
                    "title": "split python-libs subpackage", 
                    "id": "625372", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644147", 
                    "title": "Patch for get_filename in email.message when content-disposition is missing", 
                    "id": "644147", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=644761", 
                    "title": "python-libs conflict on ia64 compatlayer", 
                    "id": "644761", 
                    "issue date": "2011-01-13", 
                    "associated redhat": "RHSA-2011:0027"
                }
            }
        ], 
        "Gentoo": [
            {
                "url": "https://security.gentoo.org/glsa/200903-41", 
                "id": "GLSA-200903-41"
            }, 
            {
                "url": "https://security.gentoo.org/glsa/200904-06", 
                "id": "GLSA-200904-06"
            }
        ], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                "id": "USN-1596-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                "id": "USN-1613-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                "id": "USN-1613-2"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1616-1", 
                "id": "USN-1616-1"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}