{
    "Information": {
        "Category": [
            {
                "url": "https://cwe.mitre.org/data/definitions/118.html", 
                "id": "CWE-118", 
                "title": "Improper Access of Indexable Resource (Range Error)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/20.html", 
                "id": "CWE-20", 
                "title": "Improper Input Validation"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/726.html", 
                "id": "CWE-726", 
                "title": "OWASP Top Ten 2004 Category A5 - Buffer Overflows"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/633.html", 
                "id": "CWE-633", 
                "title": "Weaknesses that Affect Memory"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/740.html", 
                "id": "CWE-740", 
                "title": "CERT C Secure Coding Section 06 - Arrays (ARR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/741.html", 
                "id": "CWE-741", 
                "title": "CERT C Secure Coding Section 07 - Characters and Strings (STR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/742.html", 
                "id": "CWE-742", 
                "title": "CERT C Secure Coding Section 08 - Memory Management (MEM)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/743.html", 
                "id": "CWE-743", 
                "title": "CERT C Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/744.html", 
                "id": "CWE-744", 
                "title": "CERT C Secure Coding Section 10 - Environment (ENV)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/752.html", 
                "id": "CWE-752", 
                "title": "2009 Top 25 - Risky Resource Management"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/874.html", 
                "id": "CWE-874", 
                "title": "CERT C++ Secure Coding Section 06 - Arrays and the STL (ARR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/875.html", 
                "id": "CWE-875", 
                "title": "CERT C++ Secure Coding Section 07 - Characters and Strings (STR)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/876.html", 
                "id": "CWE-876", 
                "title": "CERT C++ Secure Coding Section 08 - Memory Management (MEM)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/877.html", 
                "id": "CWE-877", 
                "title": "CERT C++ Secure Coding Section 09 - Input Output (FIO)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/878.html", 
                "id": "CWE-878", 
                "title": "CERT C++ Secure Coding Section 10 - Environment (ENV)"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/970.html", 
                "id": "CWE-970", 
                "title": "SFP Secondary Cluster: Faulty Buffer Access"
            }
        ], 
        "CAPEC": [
            {
                "url": "https://capec.mitre.org/data/definitions/10.html", 
                "id": 10
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/100.html", 
                "id": 100
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/14.html", 
                "id": 14
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/24.html", 
                "id": 24
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/42.html", 
                "id": 42
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/44.html", 
                "id": 44
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/45.html", 
                "id": 45
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/46.html", 
                "id": 46
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/47.html", 
                "id": 47
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/8.html", 
                "id": 8
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/9.html", 
                "id": 9
            }
        ], 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-1912", 
                "published": "2014-02-28T19:55:05.093-05:00", 
                "id": "CVE-2014-1912", 
                "modified": "2016-03-30T17:58:32.060-04:00", 
                "summary": "Buffer overflow in the socket.recvfrom_into function in Modules/socketmodule.c in Python 2.5 before 2.7.7, 3.x before 3.3.4, and 3.4.x before 3.4rc1 allows remote attackers to execute arbitrary code via a crafted string."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/119.html", 
                "id": "CWE-119", 
                "title": "Improper Restriction of Operations within the Bounds of a Memory Buffer"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:2.5.150"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.2"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.0.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.0"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.2150"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.3"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.4"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.5"
            }, 
            {
                "id": "cpe:/a:python:python:3.4:alpha1"
            }, 
            {
                "id": "cpe:/a:python:python:3.2.2150"
            }, 
            {
                "id": "cpe:/a:python:python:3.2:alpha"
            }, 
            {
                "id": "cpe:/a:python:python:3.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.0"
            }, 
            {
                "id": "cpe:/a:python:python:3.3"
            }, 
            {
                "id": "cpe:/o:apple:mac_os_x:10.10.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.3"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.2150::~~~~x64~"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.3"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.4"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.5.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.3.0"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.3"
            }, 
            {
                "id": "cpe:/a:python:python:3.3.1"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.2:rc1"
            }, 
            {
                "id": "cpe:/a:python:python:3.3:beta2"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1:rc1"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.4"
            }, 
            {
                "id": "cpe:/a:python:python:3.3.2"
            }, 
            {
                "id": "cpe:/a:python:python:3.3.3"
            }, 
            {
                "id": "cpe:/a:python:python:3.1.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.6150"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1150"
            }, 
            {
                "id": "cpe:/a:python:python:2.7.1150::~~~~x64~"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.8"
            }, 
            {
                "id": "cpe:/a:python:python:2.6.2150"
            }, 
            {
                "id": "cpe:/a:python:python:2.7"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }, 
            {
                "id": "cpe:/a:python:python:2.5"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.66486", 
                "id": 66486
            }, 
            {
                "url": "http://www.scip.ch/?vuldb.12225", 
                "id": 12225
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "http://bugs.python.org/issue20246", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://www.trustedsec.com/february-2014/python-remote-code-execution-socket-recvfrom_into/", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "https://support.apple.com/kb/HT205031", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-2125-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.securitytracker.com/id/1029831", 
                    "vendor": "SECTRACK"
                }, 
                {
                    "url": "http://www.openwall.com/lists/oss-security/2014/02/12/16", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://www.exploit-db.com/exploits/31875", 
                    "vendor": "EXPLOIT-DB"
                }, 
                {
                    "url": "http://www.debian.org/security/2014/dsa-2880", 
                    "vendor": "DEBIAN"
                }, 
                {
                    "url": "http://pastebin.com/raw.php?i=GHXSmNEg", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html", 
                    "vendor": "APPLE"
                }, 
                {
                    "url": "http://hg.python.org/cpython/rev/87673659d8f7", 
                    "vendor": "CONFIRM"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "6.4", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "7.5", 
                    "integrity impact": "partial", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "High", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [
            {
                "url": "http://www.exploit-db.com/exploits/31875", 
                "id": 31875, 
                "file": "platforms/linux/remote/31875.py"
            }
        ], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2014-1912"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:25260", 
                "title": "SUSE-SU-2014:0576-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:25260"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:26391", 
                "title": "SUSE-SU-2014:0997-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:26391"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:26776", 
                "title": "DEPRECATED: SUSE-SU-2014:0997-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:26776"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:26568", 
                "title": "SUSE-SU-2014:1012-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:26568"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:27033", 
                "title": "DEPRECATED: SUSE-SU-2014:1006-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:27033"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:27010", 
                "title": "DEPRECATED: SUSE-SU-2014:1012-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:27010"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:26582", 
                "title": "SUSE-SU-2014:1006-1 -- Security update for Python", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:26582"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23923", 
                "title": "USN-2125-1 -- python2.6, python2.7, python3.2, python3.3 vulnerability", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23923"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Debian Security Advisory DSA 2880-1 (python2.7 - security update)", 
                "file": "deb_2880.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "702880"
            }, 
            {
                "name": "Fedora Update for python FEDORA-2014-2394", 
                "file": "gb_fedora_2014_2394_python_fc20.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "867505"
            }, 
            {
                "name": "Fedora Update for python3 FEDORA-2014-2418", 
                "file": "gb_fedora_2014_2418_python3_fc20.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "867510"
            }, 
            {
                "name": "Python socket.recvfrom_into Buffer Overflow Vulnerability Mar14 (Windows)", 
                "file": "gb_python_bof_vuln_mar14_win.nasl", 
                "family": "Buffer overflow", 
                "id": "801617"
            }, 
            {
                "name": "Ubuntu Update for python2.7 USN-2125-1", 
                "file": "gb_ubuntu_USN_2125_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841733"
            }
        ], 
        "Nessus": [
            {
                "name": "Amazon Linux AMI : python26 (ALAS-2014-292)", 
                "file": "ala_ALAS-2014-292.nasl", 
                "family": "Amazon Linux Local Security Checks", 
                "id": "72748"
            }, 
            {
                "name": "Amazon Linux AMI : python27 (ALAS-2014-293)", 
                "file": "ala_ALAS-2014-293.nasl", 
                "family": "Amazon Linux Local Security Checks", 
                "id": "72749"
            }, 
            {
                "name": "CentOS 6 : python (CESA-2015:1330)", 
                "file": "centos_RHSA-2015-1330.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "85012"
            }, 
            {
                "name": "Debian DSA-2880-1 : python2.7 - security update", 
                "file": "debian_DSA-2880.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "73065"
            }, 
            {
                "name": "Fedora 20 : python-2.7.5-10.fc20 (2014-2394)", 
                "file": "fedora_2014-2394.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "72523"
            }, 
            {
                "name": "Fedora 20 : python3-3.3.2-9.fc20 (2014-2418)", 
                "file": "fedora_2014-2418.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "72524"
            }, 
            {
                "name": "FreeBSD : Python -- buffer overflow in socket.recvfrom_into() (8e5e6d42-a0fa-11e3-b09a-080027f2d077)", 
                "file": "freebsd_pkg_8e5e6d42a0fa11e3b09a080027f2d077.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "72768"
            }, 
            {
                "name": "GLSA-201503-10 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201503-10.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "82009"
            }, 
            {
                "name": "Mac OS X < 10.10.5 Multiple Vulnerabilities", 
                "file": "macosx_10_10_5.nasl", 
                "family": "MacOS X Local Security Checks", 
                "id": "85408"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2014:041)", 
                "file": "mandriva_MDVSA-2014-041.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "72594"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2015:075)", 
                "file": "mandriva_MDVSA-2015-075.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "82328"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python3 (MDVSA-2015:076)", 
                "file": "mandriva_MDVSA-2015-076.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "82329"
            }, 
            {
                "name": "openSUSE Security Update : python (openSUSE-SU-2014:0380-1)", 
                "file": "openSUSE-2014-213.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75294"
            }, 
            {
                "name": "openSUSE Security Update : python3 (openSUSE-SU-2014:0498-1)", 
                "file": "openSUSE-2014-278.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75315"
            }, 
            {
                "name": "openSUSE Security Update : python (openSUSE-SU-2014:0518-1)", 
                "file": "openSUSE-2014-289.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75320"
            }, 
            {
                "name": "openSUSE Security Update : python3 (openSUSE-SU-2014:0597-1)", 
                "file": "openSUSE-2014-333.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75343"
            }, 
            {
                "name": "Oracle Linux 6 : python (ELSA-2015-1330)", 
                "file": "oraclelinux_ELSA-2015-1330.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "85099"
            }, 
            {
                "name": "RHEL 6 : python (RHSA-2015:1330)", 
                "file": "redhat-RHSA-2015-1330.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "84938"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL6.x i386/x86_64", 
                "file": "sl_20150722_python_on_SL6_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "85206"
            }, 
            {
                "name": "SuSE 11.3 Security Update : Python (SAT Patch Number 9075)", 
                "file": "suse_11_python-201403-140331.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "73751"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 12.04 LTS / 12.10 / 13.10 : python2.6, python2.7, python3.2, python3.3 vulnerability (USN-2125-1)", 
                "file": "ubuntu_USN-2125-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "72798"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2014-1912.html", 
                "id": "openSUSE-SU-2014:0597"
            }
        ], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20151330", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2015-1330.html", 
                    "id": "RHSA-2015:1330", 
                    "title": "RHSA-2015:1330: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=794632", 
                    "title": "Python 2.6 installation is not 64 bit clean", 
                    "id": "794632", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1046174", 
                    "title": "CVE-2013-1752 python: multiple unbound readline() DoS flaws in python stdlib", 
                    "id": "1046174", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062370", 
                    "title": "CVE-2014-1912 python: buffer overflow in socket.recvfrom_into()", 
                    "id": "1062370", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1073165", 
                    "title": "subprocess.Popen.communicate() fails with: IOError: [Errno 4] Interrupted system call", 
                    "id": "1073165", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1113527", 
                    "title": "CVE-2014-4650 python: CGIHTTPServer module does not properly handle URL-encoded path separators in URLs", 
                    "id": "1113527", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1146026", 
                    "title": "CVE-2014-7185 python: buffer() integer overflow leading to out of bounds read", 
                    "id": "1146026", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1160640", 
                    "title": "cProfile main() traceback if options syntax is invalid", 
                    "id": "1160640", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1180864", 
                    "title": "multiprocessing BaseManager serve_client() does not check EINTR on recv", 
                    "id": "1180864", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1199997", 
                    "title": "python-libs should have \"Provides: python-ordereddict\"", 
                    "id": "1199997", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223037", 
                    "title": "Python raises exception on deepcopy of instance methods", 
                    "id": "1223037", 
                    "issue date": "2015-07-22", 
                    "associated redhat": "RHSA-2015:1330"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-2125-1", 
                "id": "USN-2125-1"
            }
        ], 
        "Debian": [
            {
                "url": "https://security-tracker.debian.org/tracker/DSA-2880", 
                "id": "DSA-2880"
            }
        ], 
        "Vmware": []
    }
}